### ISSUE TITLE
Make sun position not be related to Pacific Standard Time

### ISSUE THREAD

**Issue by emperorstarfinder** [Virtual-Universe/Virtual-Universe-Stable-Dev#45]
Per discussion with greythane, make the sun position relative to being set locally. and not pacific standard time.

**Comment by NoahStarfinder** [comment]
Good morning

I am assuming you are referring to this commit: https://github.com/Virtual-Universe/Virtual-Dev/commit/faca949764a02258db8582c8180752d116ff93be

The purpose of this commit is not to go back to the Pacific Standard Time but to ensure proper accountability for the Daylight Savings Time (DST) problems.  I did however notice that I did accidently revert a piece back to the PST time zone which I will correct.  

I have also talked with CaseyraeStarfinder and BriakallistaStarfinder about getting rid of the hard coded PST time zone stuff in the upcoming viewer.  They have agreed that the time zone should be relative to the actual grid server the viewer is communicating with.  It is now also on their TODO list for the new Viewer.  This should make it a lot easier and may in fact be something that should be passed along to other TPV devs out there to ensure they adjust their viewers to be compatible with using the timezone determined by the hardware on which the grid server that a viewer is communicating with instead of PST.  Halcyon probably does use PST hardcoded as I believe they are primarily out of California as well.


Noah Starfinder
 Core Developer
 Governing Body Vice Chair - North America
 In-Galaxy Services and Features Developer
 Grid Architecture Developer
 Work Group Leader
 Grid Architecture Development Work Group
 Second Galaxy Development Team
 Email: noah@secondgalaxy.com

**Comment by NoahStarfinder** [comment]
I have corrected this in commit: https://github.com/Virtual-Universe/Virtual-Dev/commit/7078a8692ef97c7f62546463bd568d50d9a1f48a

Noah Starfinder
 Core Developer
 Governing Body Vice Chair - North America
 In-Galaxy Services and Features Developer
 Grid Architecture Developer
 Work Group Leader
 Grid Architecture Development Work Group
 Second Galaxy Development Team
 Email: noah@secondgalaxy.com
